### ISSUE TITLE
[BUG/Feature] Scaling Health compatibility.

### ISSUE THREAD

**Issue by PickyPixelStudio** [Tictim/Paraglider#103]
Hey!

We use a mod called **ScalingHealth**, that add difficulty, and health point management.
**Paraglider** just force it server config, specially `startingHearts`.

So with **ScalingHeart** mod, i want 5 hearts on start, if **Paraglider** have 10, when relogging the world (only on the relog, not the first time), the player got 10 heart, instead of 5.

We tried to make **Paraglider** same as **ScalingHeart** (5 hearts on start), it work, also after a relog, BUT, when we die, we've 1/2 heart... Yeah...

Can you make a config to turn off **Paraglider** managing player's hearts? This can fix problem with a lot other mods that managing hearts.

[ScalingHeart](https://www.curseforge.com/minecraft/mc-mods/scaling-health)

**Comment by Tictim** [comment]
The max HP algorithm, shown (here)[https://github.com/Tictim/Paraglider/blob/release/1.20.1/common/src/main/java/tictim/paraglider/impl/movement/ServerPlayerMovement.java#L82], does not modify HP values based on external, preexisting attributes. The "starting hearts" system just assumes you have 10 hearts at start and computes delta values based on that. Furthermore, if the system does not have any HP values to add (e.g. on default config, without any Heart Containers), then the attribute is not added at all.

It sounds like the mod in question has a faulty implementation; please contact the other mod, and let me know if you have anything other.

**Comment by PickyPixelStudio** [comment]
Yeah, i contact the other mod's owner, because, this problem appear also without Paraglider...
Thinks something is broken on their mod, don't really know. 

Thanks for the answer =)
