### ISSUE TITLE
Possible to add configuration resets hearts/stamina gained on death?

### ISSUE THREAD

**Issue by YngFox** [Tictim/Paraglider#107]
Title

**Comment by Tictim** [comment]
I have no plans for adding such feature in the base mod. However it is quite trivial to implement on user side, by directly accessing the [API](https://github.com/Tictim/Paraglider/blob/release/1.20.1/common/src/main/java/tictim/paraglider/api/vessel/VesselContainer.java) with either an addon or a scripting tool like KubeJS.
