### ISSUE TITLE
Make this mod use Obfuscate instead of it being a core mod!

### ISSUE THREAD

**Issue by SamhitApple** [Tictim/Paraglider#11]
I don't know much about modding in Minecraft, but I've read that Obfuscate makes it that mod devs can add custom animations, movements to the player's model. That way you don't have the risk of this being a core mod just so that the arms can be lifted!

IDK whether you have to rewrite the entire mod or simply add the Obfuscate Library and tweak something, so sorry in advance!

**Comment by Tictim** [comment]
The mod seems interesting... But I don't think it is necessary, to add external mod dependency just for one part with no known issues or serious fault. Existing solution works and we don't have to reimplement it right now.

The Obfuscate mod will be one of options to migrate in future if something breaks regarding mixin(1.16)/coremod(1.15) part, but it's out of my concern, at least for now.
