### ISSUE TITLE
Paragliding still works after dropping Paraglider

### ISSUE THREAD

**Issue by Tictim** [Tictim/Paraglider#12]
This happens because capability of item is still accessible even if its stack size is zero. Since "holding Paraglider" is checked using existence of specific capability in held item, the check couldn't tell if Paraglider item is empty or not.

Fixing this should be easy. Will commit fix for both 1.16/1.15 soon after.

**Comment by Barerock** [comment]
This is still an issue I think. I am unable to end paragliding at all, my player continues to float downward when in the air and throwing the glider out deletes the item immediately.
