### ISSUE TITLE
Stamina Icon stuck on screen - Bug

### ISSUE THREAD

**Issue by ghost** [Tictim/Paraglider#3]
The empty stamina icon gets stuck on screen. 

For it to happen,the paraglider doesn't need to be equipped. 
Both times it happend,I had it on my inventory. 
It doensn't go away until I restart the game.
Going to main menu then entering the world again does nothing.

Is yet to be tested if using the paraglider temporarily fixes it.

**Comment by Tictim** [comment]
Just not having Paraglider alone is unlikely to be the source. It might be simple things, like if you constantly depleting your stamina then it might look like the stamina wheel is stuck empty.
I need additional context to figure out what exactly happened. Or if you have some time, reproducing issues in clean instance would be appreciated.

**Comment by ghost** [comment]
I unintentionally exaggerated the issue. It doesn't go away until I restart the game,but if I simply use the paraglider again,it goes away normally.  it usually happened rarely when I go to desktop and then return.. Didn't happen without the paraglider on inventory so far.

Sorry for taking too long to respond and thanks for the nice mod :)
