### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by TheYoloPanda** [Tictim/Paraglider#31]
Forge 36.1.24
Paraglider-1.16.5-1.3.1.1

The message "paragladers failed to load" appeared
Crash report attached to ticket
[crash-2021-07-14_15.42.19-fml-PARAGLIDERS.txt](https://github.com/Tictim/Paraglider/files/6821394/crash-2021-07-14_15.42.19-fml-PARAGLIDERS.txt)

**Comment by Tictim** [comment]
Does this crash occur consistently? This seems not normal.

**Comment by TheYoloPanda** [comment]
It only occured once, if this occur again i will post it here.

**Comment by Tictim** [comment]
Closing this because there's no response. Feel free to reach out again if the same crash occurs again.
