### ISSUE TITLE
[Suggestion] Shield mechanics with stamina

### ISSUE THREAD

**Issue by Neko2n** [Tictim/Paraglider#34]
Shielding should stop stamina from regenerating, and successfully blocking a hit with a shield should consume 1/4th of the default stamina bar (250 stamina). Once the stamina bar hits zero, the player should be unable to shield until stamina fully regenerates.

Maybe heavier hits could take more stamina, with 250 stamina being the default for hits like a skeleton's arrow or a zombie's melee attack. Trying to block an axe/heavy attack that disables your shield could take half your stamina bar away or instantly drain it instead of disabling your shield. Maybe blocking attacks that would've done really high damage to you but don't count as an axe attack could also lower more stamina based on the damage that would've been dealt.

**Comment by Tictim** [comment]
You do realize this mod is heavily based on paragliding system in Breath of the Wild, right?

Some people may like this idea, but to my eyes, it's too far-fetched idea that doesn't quite gets integrated with other features.
