### ISSUE TITLE
Stamina circle at spawn

### ISSUE THREAD

**Issue by VaIerka** [Tictim/Paraglider#36]
Everytime you spawn/respawn this green circle appears. This is really annoying especially when the stamina system is completely not used and this damn circle constantly appears. Please, make it either it's not appearing on spawn or so stamina system can be fully disabled in config which will actually solve the problem

Edit: I found the solution. Making maxStamina = 0 removes green circle, but i still sugest to add special config for that.

Edit: Nuh... If maxStamina = 0 you can't do anything (sprint, swim) even if staminaconsume options are disabled

**Comment by RHSD** [comment]
I made a resourcepack that replaces stamina gui textures with single transparent pixel. Can you give it a shot? Seems to be working for me. I'll also attach my config just in case.
[nostamina.zip](https://github.com/Tictim/Paraglider/files/7259271/nostamina.zip)
[paraglider-server.txt](https://github.com/Tictim/Paraglider/files/7259281/paraglider-server.txt)
