### ISSUE TITLE
Adjusting stamina wheel position.

### ISSUE THREAD

**Issue by lol123123987** [Tictim/Paraglider#37]
Is it possible? I saw a comment on Curseforge hinting that you may bring it in the future, is that implemented and I'm just blind, or is it not here yet? If not, then it would be very useful to have. (I would customize it to make it sit in between your health and hunger)

**Comment by Orangejewce92** [comment]
so it was closed is there a way to move it?

**Comment by Tictim** [comment]
Try pressing ctrl+P ingame

**Comment by Orangejewce92** [comment]
Thank you will test this !
