### ISSUE TITLE
More Challenge Drop Configuration

### ISSUE THREAD

**Issue by TyrionReyukra** [Tictim/Paraglider#38]
It's currently not possible to have heart vessels exclusive to statue bargains.
It's possible to disable the ender dragon and raid drops, but not the wither, and disabling the vessels removes the statue bargains for hearts entirely.

A config to disable the wither rewards along with the already existing raid and ender dragon toggles would be appreciated.

Reading the comments on the mod page, it also seems that datapacks can be used to configure the trades?
An example pack would be appreciated for those of us who don't fully understand how to make mod-interacting datapacks.

**Comment by Tictim** [comment]
Hello Biokoro.

First of all, please note that vessel drop from Wither is implemented using loot modifiers, and therefore it can be disabled using datapacks. Also I think raid config option is already present in server config.

And yes, bargains(or trades, call them whatever you'd like 😛) are 100% compatible with datapacks. We do not have example pack, but all of its functions are demonstrated in recipes in the mod. Nonetheless, documentation for recipe json format would be nice.

**Comment by TyrionReyukra** [comment]
Thanks for the speedy reply,
I'm still new to github so viewing the code on here for datapack creation is a bit confusing for me haha.
After unpacking the mod and exploring a bit, I believe I can construct a basic datapack from there.

Thank you for the great mod! Allowing the stamina system for other actions such as running and swimming really helps encourage exploration. Allowing customizability through user friendly systems such as config files and datapacks really helps too.

An example pack of what's able to be changed and showcase the overall folder structure would be great for people who don't know how to view the contents of .jar files, or construct datapacks from scratch.
