### ISSUE TITLE
Inventory Profiles Next "Incompatibility"

### ISSUE THREAD

**Issue by Answordy** [Tictim/Paraglider#49]
I don't know where should I post this issue, which mod is causing it. It's not a total incompatibility, rather a visual issue.
On the bargain screen of the Godess and Horned statues the icons of the items dissapaer. Everything else works, it's just a rather annoying visual problem, not a technical one. I tried to customize and turn off inventory profiles on the bargain screen with the overlay editor, but it didn't help nor work properly, because most of the things are being rendered off-screen, they are getting cut no matter the screen resolution, as shown on the second picture.
![2022-04-22_23 46 58](https://user-images.githubusercontent.com/82783515/164801940-d29fbb1c-6bce-4a53-9782-d2a178cdef51.png)
![2022-04-22_23 57 10](https://user-images.githubusercontent.com/82783515/164801951-2ebcac49-9db0-42a8-a17e-6819a1bd34b9.png)
I posted the issue on Inventory Profiles github but i'm posting it here too because maybe the screen itself causes the issues since on my heavily modded insance it also cuts the JEI icon (down right corner), as shown on this picture.
![2022-04-22_23 39 23](https://user-images.githubusercontent.com/82783515/164802173-102dc329-3ec8-4289-b3c0-2f6b79e42f08.png)

**Comment by Tictim** [comment]
Their overlays being cut offscreen is most likely due to bargain screen occupying whole screen. This is intentional choice to make the screen not cluttered with other mod-added widgets, such as JEI ones.

For the item rendering part, no idea.

**Comment by Answordy** [comment]
Yeah, I don't mind the cutting part, the rendering is the main problem. And about that, I don't have a clue either, since I was finally able to turn Inv Profiles off for the screen, trough config, but that didn't fix it. So in the end, my conculsion is, while both mods are installed the problem will appaer, no matter the settings sadly.

**Comment by Shibva** [comment]
This issue seems to also be prelivant in JEI, the tab where bookmarked items cast over the render of this menu; there is compat methods in the mod that when applied will make the JEI menu "shift" around the UI element

**Comment by Tictim** [comment]
> This issue seems to also be prelivant in JEI, the tab where bookmarked items cast over the render of this menu; there is compat methods in the mod that when applied will make the JEI menu "shift" around the UI element

Sounds like an unrelated issue.

**Comment by Tictim** [comment]
As of 20.1.0 the bargain screen no longer uses containerscreens, so this issue should no longer appear.
