### ISSUE TITLE
Implement spirit orb related feature

### ISSUE THREAD

**Issue by Tictim** [Tictim/Paraglider#5]
Currently spirit orbs feature and everything around it is incomplete and needs redesign. There's some idea about how it should be.

By the way stranger, do you have any idea? Yes, I'm talking about *you*. Is there something you think it would be cool? Then, please share it! You're never gonna tell me about it once the work is done, and probably get mad at me because the mod sucked dick.

**Comment by Tictim** [comment]
So... Crafting recipe for spirit orb/heart container/stamina vessel is going away. It was only temporary, and will be changed to something more resembles how original game works. By original game I mean the zelda one 😅

There will be new type of statue called *Goddess Statue*. It gives 1 heart container or 1 stamina vessel for 4 spirit orb. Horned Statue will also going to be changed to selling and buying containers with emeralds. Selling container is per-player information and not per-statue information, meaning you can buy containers even if the container was bought by different statue.

**Comment by Tictim** [comment]
Goddess Statue in middle of the village makes sense. Horned Statue can be quite rare and hard to find, like underground chamber, hidden room inside village somewhere, middle of nowhere idk. Making statue hard to find and encouraging travelling to search for village or some sort of structure would do well with paraglider.

**Comment by Tictim** [comment]
Some time ago I tried to make model for Goddess Statue but wasn't quite successful. I think it's because I tried to match its size to Horned Statue. As much as I love it, it's not quite right. It's too damn tiny. It was deliberately made so I don't have to code 2-tile tall multiblock. Not that I can't, it's just annoying.

So it might be good to make another version; Bigger, 2-tile tall statues. But if I do, I might be adding current small statue as 'miniatures', with same functionality but fits in one tile. Then there's high chance it will be craftable, or at least can be 'cycle'd between normal statue and miniature.

Then still I have to make miniature goddess statue. Oh the irony. It won't gonna be the same though. I guess it would look like, uh, what's THAT thing called? The statue that spawns random leaf boi screaming 'YAHAHA!' if you put apple in front of it.

**Comment by Tictim** [comment]
I don't have very interesting idea on Spirit Orbs. I guess I'm going to shove it inside some chests and say it's done. Maybe drop one for destroying Spawners? Nah, it hardly makes any sense. Drop for killing bosses is meh either. I think leaving most of the fancy things out and keeping it simple is way to go.

**Comment by smallerYeet** [comment]
How about you take a look at the mod "[Tower's of the Wild](https://www.curseforge.com/minecraft/mc-mods/towers-of-the-wild)" It's a great mod and an opportunity to start using your orbs!
Ofc you can still do your own thing

**Comment by Tictim** [comment]
I saw the Vazkii modpack one I don't remember the name added Paraglider with Towers of the Wild. They added Paraglider item in tower chests and I think it's great introduction to Paragliders who never made one. I'm stealing that.

**Comment by Tictim** [comment]
Alright folks, I think the Spirit Orb feature is done by now. Structures are ugly, some dialogs are missing, sure. But it'll be refined in the future. I can't believe this shit took over half a year. What a fucking useless modder I am. Anyways...

After some testing and internal closed beta with me and my friends, I'm planning to release a beta build in CurseForge. Then I will take some sweet break (again) while waiting for arising issues and improvements until out of beta.

Closing this issue as it made its goal of developing Spirit Orb feature. Any other design inputs are still welcome, just not in this issue. Thanks.
