### ISSUE TITLE
Bug: Strange Paraglider Behavior when Sprinting in 1.18.2 [caused by NotEnoughAnimation

### ISSUE THREAD

**Issue by Shibva** [Tictim/Paraglider#52]
first time testing with the mod and I found that sprinting makes you "descend" with your arms pointing backward

![image](https://user-images.githubusercontent.com/38770780/173679662-0e802d32-8fe1-4e88-b122-0de721d47c12.png)
(the fact my skin is a skeleton of comical misfortune makes this bug hilarious ig)

other mods are present but the only mods Id think would do this or might do this if it's not a bug happening in the mod alone would be the following I have:

-NotEnoughAnimations; is a mod that slightly improves the player animations from eating; to overall selection improvements
-Wavey Capes; a Simple mod that animates the cape

**Comment by Shibva** [comment]
Edit: corrected image; used one from my clipboard that I was using for a post to a friend when I thought I had the bug image copied at the time I posted it

here's the image if your curious 
![image](https://user-images.githubusercontent.com/38770780/173679787-4fb48ff3-1e24-4bc6-8ea0-472290d2f7bc.png)

**Comment by Shibva** [comment]
Edit 2: NotEnoughAnimations is whats causing this when sprinting; might make a report on this on their end to prevent this from happening in certain cases

**Comment by Tictim** [comment]
Seems like they are doing some sort of arithmetic operation, likely multiplication, to the arm rotation which Paraglider manipulated beforehand. I don't think this issue should be patched from my side; contact the other mod for a fix.
