### ISSUE TITLE
Config Additions

### ISSUE THREAD

**Issue by asf4l1s** [Tictim/Paraglider#53]
Currently working on a 1.16.5 modpack that adds this alongside a lot of dungeon mods, which means theres a lot of spawners. 

I like spirit orbs but i'd also like to be able to configure how many drop from spawner/the rate at which they drop, so that heart containers feel more earned.

**Comment by Tictim** [comment]
You can use datapack to disable or modify drop rate of Spirit Orbs for spawners, since it is implemented with loot modifiers.

**Comment by asf4l1s** [comment]
No idea how to use those, oh well :/

**Comment by asf4l1s** [comment]
I've spent the past two days trying to figure out how to make a datapack that would fix the problem, scoured youtube and google, asked on reddit and in discords, but I haven't been able to get anything more than what appears to be a loot table for mobdrops - any advice on where to look?
