### ISSUE TITLE
[Paraglider/]: Couldn't find player with UUID 46647bf9-af98-43cc-92bc-f409b1d8f7fc

### ISSUE THREAD

**Issue by WatermelonFroggy** [Tictim/Paraglider#54]
Getting [Paraglider/]: Couldn't find player with UUID 46647bf9-af98-43cc-92bc-f409b1d8f7fc which then forces me out of the server

**Comment by Tictim** [comment]
The error message is unrelated to the server disconnecting issue.

It's unclear if the issue is related to the mod or not. Could you provide the client/server log, instead of the one line cut off?

**Comment by Tictim** [comment]
Closed due to inactivity.
