### ISSUE TITLE
Towers of the Wild "Reworked" Datapack Integration - Feature Update

### ISSUE THREAD

**Issue by thisguycolton** [Tictim/Paraglider#56]
For my 1.18.2 server I wanted to have this mod as well as Towers of the Wild. However, they are not updating their mod to 1.18.2. They have created a datapack instead here: https://www.curseforge.com/minecraft/texture-packs/towers-of-the-wild-reworked-datapack

The main problem with this is the loot table names have been adjusted. So the chests don't get a paraglider. 

So I downloaded the your source code here and changed one line to get it working!
On [this file](https://github.com/Tictim/Paraglider/blob/release/1.18.2/src/generated/resources/data/paraglider/loot_modifiers/towers_of_the_wild/chest.json) The "loot_table_id" needs updated to: "towers_of_the_wild_reworked:tower_chest" 

And unfortunately the "ocean_chest" seems missing from the datapack, so  just that change worked for me.

**Comment by szunakabeats** [comment]
yea this would be awesome :)

**Comment by szunakabeats** [comment]
is there a datapack for this ? or a update ?

**Comment by Tictim** [comment]
Implemented in both 1.19 release and upcoming 1.18 release.
