### ISSUE TITLE
[1.19.2] Structures are still generating with config option set to false.

### ISSUE THREAD

**Issue by murao-kun** [Tictim/Paraglider#59]
![image](https://user-images.githubusercontent.com/110398598/187875239-0b09eba8-ef0a-4ceb-a852-11877daeb993.png)
![image](https://user-images.githubusercontent.com/110398598/187875274-c933b1d1-0675-4680-ab14-1ed882c4ef25.png)
[debug.log](https://github.com/Tictim/Paraglider/files/9468398/debug.log)
[latest.log](https://github.com/Tictim/Paraglider/files/9468400/latest.log)

**Comment by murao-kun** [comment]
I made sure to restart game and etc. This is the bug that was discovered after two days of config was set.

**Comment by Tictim** [comment]
Yes, it's a known issue. Due to the structures being registered with datapacks (starting from 1.18), you need to use datapacks to disable them.

Note the option still disables village structures correctly; it just doesn't work for worldgen features.
