### ISSUE TITLE
Feature Request: Stamina-Based Combat Configuration

### ISSUE THREAD

**Issue by dongbeater3000** [Tictim/Paraglider#60]
Having a configuration setting to drain stamina on an attack would be a great addition. It already can be used to drain when sprinting, which is a really neat feature.  This would be perfect if it had compatibility with the [Better Combat mod](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus), and could really open up some interesting possibilities for modpacks.

In general, I think the stamina system could benefit from additional extensions, such as draining on tool use (block-break) for challenge packs.

This might need some iterating, but I think it could be really cool if it was done right.

**Comment by Tictim** [comment]
First of all, the stamina system is heavily focused for bringing BotW paragliding to Minecraft, and any idea expanding the system further is out of the scope for this mod. Even if it's toggle-able in config, it's still a considerable amount of dev work/future maintenance work put in. And I don't see such feature being used that widely, as sizable amount of users don't even use stamina system.

I am willing to provide necessary support for whatever add-on making such feature, but I don't think it's a good idea to include it in base mod.

**Comment by RedPxnda** [comment]
https://www.curseforge.com/minecraft/mc-mods/sotw-stamina-of-the-wild
WIP and not yet approved, but here
