### ISSUE TITLE
Can't change amount maximum amount of heart cannisters

### ISSUE THREAD

**Issue by ZGLAZEDONUTX** [Tictim/Paraglider#61]
having trouble changing the maximum amount of heart cannisters. as i want to drop it too 10 instead of 20 but every time I change it, it doesn't work

**Comment by Tictim** [comment]
Please specify which version you are playing.
Also define 'doesn't work' - what specific value did you change in the config? How the behavior deviated from your expectation?

**Comment by Tictim** [comment]
Closed due to inactivity.
