### ISSUE TITLE
1.19.2 Randomly failing to load UUID causing DEBUG level crash.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Tictim/Paraglider#62]
- Paraglider-1.19.2-1.7.0.1

This does not happen 100% of the time its why it was so hard to track down. Please note make sure you mod is compatible with ``https://www.curseforge.com/minecraft/mc-mods/no-chat-reports`` as large chunks of the community including myself don't support Mojang/Microsofts decision to force use to use their moderation system.

**Comment by Tictim** [comment]
Please provide log or crash report at least. I don't even know what 'DEBUG level crash' was supposed to even mean, let alone the cause.
Also, please elaborate more on the incompatibility with No Chat Reports, as me mod has no incompatibility baked in afaik.

**Comment by P3rf3ctXZer0** [comment]
The issues run deeper than this mod ... thanks for working with me I will close this till I figure out how deep. I will reopen things if it turns out to be the same issue.
