### ISSUE TITLE
Adding Feathers Stamina Support - 1.19.2 Forge

### ISSUE THREAD

**Issue by zachsai** [Tictim/Paraglider#66]
Implementing Stamina with the Feathers API which is used with the Elenai Dodge 2 mod.
Using the same stamina mechanic for different mods makes it more immersive and would be cool to see.
This could be a toggle-able option in the config.

https://www.curseforge.com/minecraft/mc-mods/feathers

**Comment by Tictim** [comment]
I've checked out the code but it doesn't seem to be a viable replacement for current stamina system of Paraglider's. Paraglider and the aforementioned mod have features missing on another, so neither overwriting Feathers' stamina state with Paraglider's stamina state nor the other way would go smoothly.

Unrelated note, the stamina system provided by the mod doesn't seem to be very spoof-proof. It's quite easy to just, uh, [literally lie over the current stamina state](https://github.com/ElenaiDev/Feathers/blob/b96980d2fd451c0b53d2918f491c55e4530d7447/src/main/java/com/elenai/feathers/networking/packet/FeatherSyncCTSPacket.java#L10) and enjoy infinite stamina. Personally I endorse this kind of game design that gives advantage to tech-savvy players, as opposed to players with archetypal 'gamer' skills often praised, but maybe it's not that great when it comes to general-purpose features designed to be shared between other mods. Just maybe.
