### ISSUE TITLE
Feature Request - Add support for configurable movement speed

### ISSUE THREAD

**Issue by skruis** [Tictim/Paraglider#7]
First with, love the mod! If possible, could you add an option to the config to allow admins to control movement speed while the glider is in use?

Thanks!

bus

**Comment by Tictim** [comment]
Yeah, I could do that. I think the implementation would be pretty easy... Just some flag to manage speed attribute in `Movement` class.

But free time is very scarce these days, and I'm devoting all my free time to something more stupid. Pardon me if I leave this issue for, idk, a month or two. I hope it's not THAT long.

**Comment by skruis** [comment]
Tictim, I completely understand and I appreciate you responding. You can close the issue if you want to. I merely wanted to make a suggestion. Thanks for sharing your work with the rest of us!
