### ISSUE TITLE
Suggestion: Add a config to disable bartering for stamina and/or heart vessels.

### ISSUE THREAD

**Issue by Ezeyra** [Tictim/Paraglider#75]
Would be nice if you could add a config to disable bartering for stamina and/or heart vessels. Also maybe to disable spirit orbs from dropping after you break a spawner.

**Comment by Tictim** [comment]
They all exist as config options already.

**Comment by Ezeyra** [comment]
as far as I can tell you aren't able to disable them separately. for example if I want heart containers to be only available through challenges but not through bargaining. Same with spirit orbs you can only disable them spawning altogether not just from breaking a spawner. I know its very specific and of course no problem if this isn't added. I don't know how it works behind the scenes so I'm not sure if what I'm asking is a simple thing or not.

**Comment by Tictim** [comment]
If you want to adjust the feature in more granular level then you need to use datapacks.
* You can disable bargain recipes by removing datapack entry for each of them. Or if you have some other framework with more advanced functionalities, removing recipe by ID would probably work.
* You can disable spawner dropping Spirit Orbs by removing the [loot modifier](https://github.com/Tictim/Paraglider/blob/release/1.19.3/src/generated/resources/data/paraglider/loot_modifiers/spirit_orbs/spawner.json) adding the drop from the list.

**Comment by Ezeyra** [comment]
Ok I’ll look into it, thanks for the help!
