### ISSUE TITLE
 Removing hearts from other players

### ISSUE THREAD

**Issue by asant04** [Tictim/Paraglider#76]
Is it possible to remove hearts from other players in a multiplayer server? Removing the mod does not remove hearts, unfortunately. When I started the server my I never put a cap on the hearts cuz i didnt know about it, and now my friend has 200 health and doesnt die :/ I doubt I can get them to use the anti vessel lol. pls help

**Comment by Tictim** [comment]
Starting from 20.1.0 you can use command `/paraglider set heart_container @player 1` to force set player's Heart Container.

Heart Container won't give you 200 HP btw, unless you changed the config option.

**Comment by Asterveila** [comment]
is there any way to do this in older versions? i'm on 1.18.2 (1.6.0.6) and i need to reset the hearts of players on my server

**Comment by Tictim** [comment]
A couple of other, less convenient ways are available.
* You can directly edit the save data. The data should be in the player save file, under capability section.
* If you have a competent scripting mod that can access Java code (aka kubejs lol) then you can probably access the code-side API directly to set the amount of heart container.
* I think if you edit the config value for maximum amount of hearts a player can take, then the HP value of the player should be re-adjusted on server reload/player rejoin.
* Lastly, you can force the player to eat Anti Vessel... somehow.

**Comment by Asterveila** [comment]
The third method works! i set the max amount to 0 and disabled heart containers temporarily and it worked just fine, tysm!
