### ISSUE TITLE
Suggestion - Spirit Orb option

### ISSUE THREAD

**Issue by ceifadorcinixtru** [Tictim/Paraglider#78]
It would be nice to have an option in the spirit orb session to separate the spawner drop and the chest loot drop in the spirit orb options. I know that you can change this through datapacks, but the majority of the people dont know how to do it and it will be an easier way to configure this in modpacks that add a lot of dungeons with lot of spawners inside.

**Comment by Tictim** [comment]
Corresponding server config options were added in 20.1.0.
