### ISSUE TITLE
[Question] is there a config to set how many Spirit Orbs are required per vessel?

### ISSUE THREAD

**Issue by HanatakeYurii** [Tictim/Paraglider#83]
As the title says, I would like to be able to set how many Spirit Orbs are required for donation a Goddess Statue to receive a Vessel, because in my modpack there are so many dungeons with spawners that we obtain them too easily.

If you don't want to disrupt the Legend Of Zelda feel (4 Orbs for 1 Vessel), maybe give the ability to change the chance of dropping an Orb.

EDIT: is there maybe something I could do myself with a datapack?

**Comment by Tictim** [comment]
By modifying the datapack, yes. All bargain recipes are added with JSON datapack entries, you can find it in recipe folder.
