### ISSUE TITLE
Suggestion: Make Upwind Particle Density customisable in Config

### ISSUE THREAD

**Issue by Marteinstr** [Tictim/Paraglider#88]
Hello, it is pretty much all in the title.

While performance-wise the number of particles doesn't seem to cause much lag in itself, the visual clutter it causes gets pretty bad, especially when gliding over lava lakes (i'm sorry if you didn't intend that but it is just one of the greatest QoL things your mod does). 

And even single sources like campfires can sometimes generate upwards of 15-20+ particles combined to their smoke effect, which with other sources of visual clutter/lag gets pretty bad.

So yeah it would be cool if you could add to the config file a line to control the upwind particles density. 
0(disabled) to 100(full) let's say as an example.

Sorry for the bother, have a nice day and good continuation.

**Comment by Tictim** [comment]
This feature got implemented in 20.1.0. You can access the option in client settings. (Press Ctrl+P in-game)

In addition, the amount of particles generated for individual wind sources now decreases proportional to total number of wind sources in the area, so large number of wind sources should not be much of a problem.
