### ISSUE TITLE
Heart Container and Stamina Vessel Description Switched on all Statues

### ISSUE THREAD

**Issue by emanuelal99** [Tictim/Paraglider#90]
Hovering over the heart in the spirit orb selection UI shows stamina and vice versa.

Fabric 1.20.1

**Comment by TeraNovell** [comment]
Same problem here. For more detailed description:

![image](https://github.com/Tictim/Paraglider/assets/16338782/b090e920-f32f-492e-915a-5064a098dfc9)

![image](https://github.com/Tictim/Paraglider/assets/16338782/d72c4114-8c99-4509-a360-c3eaf01d965c)

Mod: 20.1.1
MC: 1.20.1
Forge: 47.2.1

It would be nice if this problem could be fixed. Thanks in advance ^^
