### ISSUE TITLE
[suggestion] sky diving  

### ISSUE THREAD

**Issue by jojofenin99** [Tictim/Paraglider#93]
I think being able to do some sort of dive in the air while not using your paraglider would be very cool and add so many more possibility's and opportunities for this mod

**Comment by jojofenin99** [comment]
and maybe something like bullet time could be implemented with the stamina system but only in a radius for multiplayer compatibility

**Comment by Tictim** [comment]
Additional movement features, aside from paragliding, are out of scope for this mod.
