### ISSUE TITLE
[Idea] Stamina wheel does not show when no setting use it

### ISSUE THREAD

**Issue by Joshernoob** [Tictim/Paraglider#98]
Feel like if staminaVessels = false or paraglidingConsumesStamina = false/ runningAndSwimmingConsumesStamina = false are set the wheel for Stamina should not show up in game as an overlay

along with this be great to have a config for client to disable or move it, I'm on 1.20.1 so there may be one on older version but its not there for version I'm playing why I'm mentioning it

to explain in more detail, would make since that you don't need the Stamina wheel while nothing using it so if all things using it are false or the overall setting that effects both is false then it shouldn't the overlay be off as well?

**Comment by Tictim** [comment]
It was supposed to be hidden if no stamina-consuming actions are defined, but the system didn't work because I used < instead >. It'll be fixed in the next update.

For moving stamina wheel's position, press Ctrl+P ingame. There's no option to disable stamina wheel overlay.
